/*
 * installers.js — אנשי אלומיניום לפי אולם של קליל (בונוס 1, שיעור 4).
 * המקור: Apify, Google Maps Scraper. שלוש סריקות (חיפה, נתניה, מרכז), איחוד וסינון
 * לעסקי אלומיניום/חלונות/תריסים, ולכל אולם 30 הקרובים ביותר ברדיוס 80 ק"מ.
 * הנתונים ציבוריים (גוגל מפות). לרענון: להריץ שוב את הסריקה ולהחליף את הקובץ.
 */
window.INSTALLERS = {
 "meta": {
  "source": "Apify · compass/crawler-google-places (Google Maps Scraper)",
  "runs": [
   "gOqXSJFvvKPHyZoR9",
   "H2BjSlj1BzraThIsg",
   "3eMwGMWvUKC9XyM3C"
  ],
  "query": "חלונות אלומיניום / אלומיניום, רדיוס 80 ק\"מ מכל אולם",
  "fetchedAt": "03.10.2026"
 },
 "halls": [
  {
   "id": "haifa",
   "name": "אולם חיפה",
   "lat": 32.794,
   "lng": 34.989,
   "places": [
    {
     "name": "לנדמן - אלומיניום בע\"מ",
     "score": 5,
     "reviews": 12,
     "city": "חיפה",
     "phone": "+972 4-951-8000",
     "website": "https://www.aluminum.org.il/",
     "placeId": "ChIJFRcm-gW7HRURPzco-UNSU88",
     "lat": 32.7895,
     "lng": 34.9873,
     "category": "יועץ הנדסי"
    },
    {
     "name": "גולן פרוייקט אלומיניום גדרות שערים פרגולות מאלומיניום.",
     "score": 5,
     "reviews": 1,
     "city": "חיפה",
     "phone": "+972 50-531-3777",
     "website": "",
     "placeId": "ChIJ2wcIpoe7HRURuxtBjFaM5ac",
     "lat": 32.805,
     "lng": 34.9877,
     "category": "ספק אלומיניום"
    },
    {
     "name": "חלונות אלומיניום בחיפה - אלום יוסי חיפה",
     "score": 4.2,
     "reviews": 5,
     "city": "חיפה",
     "phone": "+972 50-526-1066",
     "website": "https://www.aluminumhaifa.com/",
     "placeId": "ChIJ5xdXAU66HRURQlSBusHDcFg",
     "lat": 32.8066,
     "lng": 35.0006,
     "category": "חלון אלומיניום"
    },
    {
     "name": "רן דיור",
     "score": 5,
     "reviews": 4,
     "city": "חיפה",
     "phone": "+972 4-867-1444",
     "website": "",
     "placeId": "ChIJY761UpW7HRURMcK5Zc6RiEQ",
     "lat": 32.8022,
     "lng": 35.0099,
     "category": "ספק מסגרות אלומיניום"
    },
    {
     "name": "פרגולות אלומיניום - ירון פרגולות",
     "score": 3,
     "reviews": 2,
     "city": "חיפה",
     "phone": "+972 73-374-5192",
     "website": "",
     "placeId": "ChIJrfqJKFMVHRURM-qNIu19DnM",
     "lat": 32.8137,
     "lng": 34.9931,
     "category": "קבלן גדרות"
    },
    {
     "name": "תריסי רמז",
     "score": 4.6,
     "reviews": 26,
     "city": "חיפה",
     "phone": "+972 4-832-2022",
     "website": "",
     "placeId": "ChIJZ7Z1qvW6HRUR7LWkmHpZVds",
     "lat": 32.79,
     "lng": 35.0136,
     "category": "חנות לאביזרי חלונות"
    },
    {
     "name": "תיקוני תריסים ורשתות בחיפה והקריות",
     "score": 5,
     "reviews": 2,
     "city": "חיפה",
     "phone": "+972 50-722-5885",
     "website": "https://sites.google.com/view/callusnow1/",
     "placeId": "ChIJ05wR4pG7HRURRWOXQV6kFBA",
     "lat": 32.79,
     "lng": 35.0137,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלום גוונים חוה",
     "score": 5,
     "reviews": 22,
     "city": "חיפה",
     "phone": "+972 73-783-8740",
     "website": "https://www.algvanim.co.il/",
     "placeId": "ChIJg_nIS2C7HRURoS7NAPCH-dA",
     "lat": 32.8109,
     "lng": 35.0054,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אלום שי-סמי",
     "score": 5,
     "reviews": 4,
     "city": "חיפה",
     "phone": "+972 52-241-0076",
     "website": "",
     "placeId": "ChIJV8-_zMW7HRURtDH-pBuLYWU",
     "lat": 32.8106,
     "lng": 35.0056,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אלום רמז",
     "score": 5,
     "reviews": 1,
     "city": "חיפה",
     "phone": "+972 52-279-5261",
     "website": "",
     "placeId": "ChIJmRQWyPS6HRURCgEHXn4cZYU",
     "lat": 32.788,
     "lng": 35.0162,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלום רויאל",
     "score": 5,
     "reviews": 41,
     "city": "חיפה",
     "phone": "+972 52-371-0705",
     "website": "https://www.alumroyal.co.il/",
     "placeId": "ChIJwfQ4lOjCbwwRVyfKiYR9iFo",
     "lat": 32.8168,
     "lng": 35.0001,
     "category": "ספק אלומיניום"
    },
    {
     "name": "חלונות אלומניום ותריסים בחיפה - אלום מרון",
     "score": 5,
     "reviews": 5,
     "city": "חיפה",
     "phone": "+972 50-964-1714",
     "website": "",
     "placeId": "ChIJNSU90Sq7HRURv5AA-fPALto",
     "lat": 32.8193,
     "lng": 34.9945,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלום ליאת",
     "score": 5,
     "reviews": 1,
     "city": "חיפה",
     "phone": "+972 4-862-3748",
     "website": "",
     "placeId": "ChIJ7UxuHma6HRURivxi7dgvapM",
     "lat": 32.7998,
     "lng": 35.0212,
     "category": "ספק אלומיניום"
    },
    {
     "name": "סוככי הזהב",
     "score": 4.2,
     "reviews": 10,
     "city": "חיפה",
     "phone": "+972 1-700-704-653",
     "website": "http://www.awgold.co.il/",
     "placeId": "ChIJkY43xMywHRURNohjaoIpo40",
     "lat": 32.7957,
     "lng": 35.0223,
     "category": "חלון אלומיניום"
    },
    {
     "name": "חלונות ותריסים בחיפה - אלומיניום אניס",
     "score": 5,
     "reviews": 2,
     "city": "חיפה",
     "phone": "+972 50-469-9591",
     "website": "",
     "placeId": "ChIJyeOOFCu7HRUR-RnLBOL-klM",
     "lat": 32.8233,
     "lng": 34.9813,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלומנט תעשיות אלומיניום",
     "score": 5,
     "reviews": 2,
     "city": "טירת כרמל",
     "phone": "+972 54-553-8270",
     "website": "",
     "placeId": "ChIJR_xemSClHRURKrusJjrnNBk",
     "lat": 32.7672,
     "lng": 34.9674,
     "category": "ספק חלונות"
    },
    {
     "name": "אלומנט עמנואל אלומיניום",
     "score": 2.5,
     "reviews": 4,
     "city": "טירת כרמל",
     "phone": "+972 50-521-8814",
     "website": "",
     "placeId": "ChIJU1KBU0q7HRURjeEzDf_mgo4",
     "lat": 32.7621,
     "lng": 34.973,
     "category": null
    },
    {
     "name": "אלום בל-פלא",
     "score": 2.5,
     "reviews": 2,
     "city": "נשר",
     "phone": "+972 52-722-0383",
     "website": "",
     "placeId": "ChIJX3XLTJC7HRURxkqHEYUJLgM",
     "lat": 32.8208,
     "lng": 34.9635,
     "category": "חלון אלומיניום"
    },
    {
     "name": "יוסי הרוש חלונות אלומיניום בחיפה",
     "score": 3.4,
     "reviews": 5,
     "city": "חיפה",
     "phone": "+972 52-266-3399",
     "website": "",
     "placeId": "ChIJhd_Ctw0THRURHyd9U9krfaQ",
     "lat": 32.7857,
     "lng": 35.034,
     "category": "חלון אלומיניום"
    },
    {
     "name": "תריסי ליאל - תיקון תריסים בחיפה",
     "score": 5,
     "reviews": 255,
     "city": "נשר",
     "phone": "+972 52-297-8855",
     "website": "",
     "placeId": "ChIJY6OeV6sTHRURPTl4kIxdiD0",
     "lat": 32.7723,
     "lng": 35.0478,
     "category": "חנות תריסים ווילונות"
    },
    {
     "name": "EMP אלומיניום בחיפה | חלונות אלומיניום | סגירת מרפסת ופרגולות",
     "score": 5,
     "reviews": 40,
     "city": "חיפה",
     "phone": "+972 52-376-8987",
     "website": "http://www.emp-aluminium.co.il/",
     "placeId": "ChIJOQBgsvS3HRURLnQwa7_nucY",
     "lat": 32.822,
     "lng": 35.0496,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלום צידן",
     "score": 5,
     "reviews": 120,
     "city": "חיפה",
     "phone": "+972 50-844-7388",
     "website": "https://www.alumtzidan.co.il/",
     "placeId": "ChIJqfw4wza7HRURzFIKPDR2Zxs",
     "lat": 32.8073,
     "lng": 35.0601,
     "category": "ספק אלומיניום"
    },
    {
     "name": "א.א. אלומיניום",
     "score": 4.5,
     "reviews": 11,
     "city": "חיפה",
     "phone": "+972 52-840-9419",
     "website": "",
     "placeId": "ChIJmWvOhb-xHRURwnVQ8o2mu9s",
     "lat": 32.8081,
     "lng": 35.0655,
     "category": "חלון אלומיניום"
    },
    {
     "name": "תריסי איכות בע\"מ",
     "score": 4.9,
     "reviews": 14,
     "city": "קרית אתא",
     "phone": "+972 52-561-9892",
     "website": "",
     "placeId": "ChIJ6X0RbkBIHRURrmyFUqy9HjQ",
     "lat": 32.8039,
     "lng": 35.0681,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "פרגולנד",
     "score": 4.8,
     "reviews": 489,
     "city": "קרית אתא",
     "phone": "+972 4-840-2092",
     "website": "http://www.pergulandshop.co.il/",
     "placeId": "ChIJR3k0u4G6HRUR3TykRXDxPFY",
     "lat": 32.8,
     "lng": 35.0706,
     "category": "יבואן"
    },
    {
     "name": "אלום שנער",
     "score": 5,
     "reviews": 34,
     "city": "חיפה",
     "phone": "+972 54-774-2499",
     "website": "http://www.alumshenar.co.il/",
     "placeId": "ChIJH_iVuOa7HRURTWwZCZ1GBBI",
     "lat": 32.8342,
     "lng": 35.0618,
     "category": "ספק אלומיניום"
    },
    {
     "name": "תריסי לי-שי - תיקון תריסים בחיפה והקריות",
     "score": 5,
     "reviews": 27,
     "city": null,
     "phone": "+972 52-889-8855",
     "website": "",
     "placeId": "ChIJYZlPKCB-nykRAoxVX2DbyjE",
     "lat": 32.7438,
     "lng": 35.0517,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אינפיניטי אלומניום בע\"מ",
     "score": 4.3,
     "reviews": 15,
     "city": "קרית אתא",
     "phone": "+972 52-809-0809",
     "website": "",
     "placeId": "ChIJN4CTIdewHRURg59GiDcACkc",
     "lat": 32.8036,
     "lng": 35.0787,
     "category": "ספק אלומיניום"
    },
    {
     "name": "תריסי מלכה - תיקון תריסים בחיפה",
     "score": 5,
     "reviews": 32,
     "city": null,
     "phone": "+972 4-880-8080",
     "website": "https://trisim-malka.co.il/",
     "placeId": "ChIJD-O_V-a7HRUR7VvC4Wvszwk",
     "lat": 32.7002,
     "lng": 35.0392,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "א. פישלר אלומיניום דיזיין Aluminum Design פרגולות חשמליות",
     "score": 4.4,
     "reviews": 67,
     "city": null,
     "phone": "+972 72-392-8991",
     "website": "https://www.alumfishler.com/",
     "placeId": "ChIJEVMV_v26HRURgDmA5-RKhZQ",
     "lat": 32.545,
     "lng": 35.2814,
     "category": "קבלן בנייה"
    }
   ]
  },
  {
   "id": "netanya",
   "name": "אולם נתניה",
   "lat": 32.275,
   "lng": 34.8616,
   "places": [
    {
     "name": "ויטבסקי - פרגולות אלומיניום ופתרונות הצללה בהתאמה אישית",
     "score": 4.8,
     "reviews": 26,
     "city": "נתניה",
     "phone": "+972 53-774-0201",
     "website": "https://www.vitebsky.co.il/",
     "placeId": "ChIJ97zUyMhBHRURCqZM-khCzE4",
     "lat": 32.2928,
     "lng": 34.8523,
     "category": "יצרן פרגולות וגגונים לרכב"
    },
    {
     "name": "רמי תיקונים",
     "score": 5,
     "reviews": 30,
     "city": "נתניה",
     "phone": "+972 50-861-0006",
     "website": "",
     "placeId": "ChIJ2WwV1yZPlYQRAcs1bRRlzyU",
     "lat": 32.2993,
     "lng": 34.8574,
     "category": "חלון אלומיניום"
    },
    {
     "name": "www.Alum-design.co.il",
     "score": 5,
     "reviews": 1,
     "city": "Tel Ytshak",
     "phone": "+972 58-788-6764",
     "website": "https://alum-design.co.il/",
     "placeId": "ChIJBYRntns_HRURIk-5Uc3BO8U",
     "lat": 32.2506,
     "lng": 34.8717,
     "category": "חלון אלומיניום"
    },
    {
     "name": "שחף (שחבר) אלומיניום בע\"מ",
     "score": 3.7,
     "reviews": 3,
     "city": "אבן יהודה",
     "phone": "+972 9-746-7496",
     "website": "http://www.shahaf-aluminium.co.il/",
     "placeId": "ChIJez5pWPc_HRURcjwAuhuYImQ",
     "lat": 32.2795,
     "lng": 34.8928,
     "category": "חלון אלומיניום"
    },
    {
     "name": "מ.ד. מערכות אלומיניום מתקדמות בע\"מ",
     "score": 4.3,
     "reviews": 25,
     "city": "אבן יהודה",
     "phone": "+972 9-861-6606",
     "website": "http://www.md-alum.co.il/",
     "placeId": "ChIJ4cQ3two_HRURr1caed-wnrM",
     "lat": 32.2788,
     "lng": 34.8942,
     "category": "ספק חלונות"
    },
    {
     "name": "ישראל אלומיניום",
     "score": 5,
     "reviews": 3,
     "city": "נתניה",
     "phone": "+972 50-734-0206",
     "website": "http://62f12c7dc2a32.site123.me/",
     "placeId": "ChIJ9frBxQFAHRURSCEWd6DaUAY",
     "lat": 32.3169,
     "lng": 34.8587,
     "category": "חלון אלומיניום"
    },
    {
     "name": "ברגמן - חלונות אלומיניום",
     "score": 5,
     "reviews": 1,
     "city": "נתניה",
     "phone": "+972 54-200-0770",
     "website": "http://bergmans.co.il/",
     "placeId": "ChIJi7hrAsk_HRUReEKYaJZz810",
     "lat": 32.3172,
     "lng": 34.8731,
     "category": "ספק חלונות"
    },
    {
     "name": "Atid Alumunium",
     "score": 5,
     "reviews": 1,
     "city": "נתניה",
     "phone": "+972 54-774-7884",
     "website": "http://www.atidalum.com/",
     "placeId": "ChIJgdrQ0BQ_HRURJ7rIevWt490",
     "lat": 32.3161,
     "lng": 34.8763,
     "category": "חלון אלומיניום"
    },
    {
     "name": "הסורגים השקופים, פטנט עולמי | קליר גארד ישראל",
     "score": 5,
     "reviews": 167,
     "city": "נתניה",
     "phone": "+972 52-607-8744",
     "website": "https://clear-guard.com/",
     "placeId": "ChIJq0cgj18_HRUReNldeOuh6os",
     "lat": 32.3177,
     "lng": 34.8758,
     "category": "ספק אלומיניום"
    },
    {
     "name": "מסגרית יואל - משקופים עיוורים לחלונות אלומיניום",
     "score": 5,
     "reviews": 3,
     "city": "נתניה",
     "phone": "+972 50-534-9908",
     "website": "",
     "placeId": "ChIJ7cQzAOM_HRURhAneUzUJKNM",
     "lat": 32.3177,
     "lng": 34.8758,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "זכוכית לינוי בע\"מ - פרינטה",
     "score": 5,
     "reviews": 118,
     "city": "נתניה",
     "phone": "+972 50-530-9530",
     "website": "http://www.pariente.co.il/",
     "placeId": "ChIJEXeqJ-M_HRUR7R_aCd8T2xQ",
     "lat": 32.3198,
     "lng": 34.8737,
     "category": "שירות זגגות"
    },
    {
     "name": "שובה אלומיניום בע\"מ",
     "score": 4,
     "reviews": 4,
     "city": "נתניה",
     "phone": "+972 50-728-0157",
     "website": "https://www.instagram.com/shuva.aluminum",
     "placeId": "ChIJYcgtpFgVHRUR_OMKvXb-Qu8",
     "lat": 32.319,
     "lng": 34.8794,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "פתח, חלון ודלת בע\"מ",
     "score": 4.5,
     "reviews": 25,
     "city": "נתניה",
     "phone": "+972 9-887-3311",
     "website": "http://www.petach.co.il/",
     "placeId": "ChIJTQTdT14VHRURtbIHINk0KJI",
     "lat": 32.3211,
     "lng": 34.8735,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "מקצועני אלומיניום - M - בע\"מ - Aluminum pro - עבודות אלומיניום.",
     "score": 5,
     "reviews": 7,
     "city": "נתניה",
     "phone": "+972 72-393-2089",
     "website": "https://pro-aluminum.co.il/",
     "placeId": "ChIJY4TSWBIVHRURhzJ1_WYcB-E",
     "lat": 32.3206,
     "lng": 34.882,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "BTS פרגולות אלומיניום סגורות",
     "score": 5,
     "reviews": 1,
     "city": "נתניה",
     "phone": "+972 79-580-0203",
     "website": "",
     "placeId": "ChIJEVabLbUVHRUR3xUr2-Azzfs",
     "lat": 32.3226,
     "lng": 34.8735,
     "category": "יצרן פרגולות וגגונים לרכב"
    },
    {
     "name": "כפיר עבודות אלומיניום",
     "score": 4.8,
     "reviews": 19,
     "city": "נתניה",
     "phone": "+972 52-575-7703",
     "website": "http://kfiral.co.il/",
     "placeId": "ChIJO1CvqL9rHRUR1j9-y22u_Yg",
     "lat": 32.3289,
     "lng": 34.8616,
     "category": "חלון אלומיניום"
    },
    {
     "name": "וולקו חיפוי אלומיניום",
     "score": 5,
     "reviews": 4,
     "city": "נתניה",
     "phone": "+972 72-372-6201",
     "website": "",
     "placeId": "ChIJ8cxg7ZZrHRUR1Pb16VQu6JE",
     "lat": 32.3297,
     "lng": 34.8597,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אלומיניום רעננה בע'מ",
     "score": 4.4,
     "reviews": 7,
     "city": "כפר סבא",
     "phone": "+972 54-767-7760",
     "website": "https://alominumrahanana.co.il/",
     "placeId": "ChIJQfDUKHM5HRUROCXDUWHsqsw",
     "lat": 32.1993,
     "lng": 34.8888,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אלומיניום השרון",
     "score": 4.4,
     "reviews": 13,
     "city": "רעננה",
     "phone": "+972 9-740-8977",
     "website": "",
     "placeId": "ChIJt6sioWE4HRURXEH97I5HG5s",
     "lat": 32.1972,
     "lng": 34.8807,
     "category": "חנות תריסים ווילונות"
    },
    {
     "name": "אלום רענן",
     "score": 5,
     "reviews": 1,
     "city": "רעננה",
     "phone": "+972 9-742-6932",
     "website": "https://www.alumraanan.co.il/",
     "placeId": "ChIJp2jNmWE4HRURW2C2zbPJATc",
     "lat": 32.1975,
     "lng": 34.8803,
     "category": "ספק מסגרות אלומיניום"
    },
    {
     "name": "מנצור -פרגולות גדרות שערים",
     "score": 5,
     "reviews": 10,
     "city": "רעננה",
     "phone": "+972 9-760-3602",
     "website": "",
     "placeId": "ChIJw0IaNl05HRUR-aakSp8rdyQ",
     "lat": 32.1925,
     "lng": 34.8814,
     "category": "משרדי החברה"
    },
    {
     "name": "רמי פרגולות אלומיניום",
     "score": 3,
     "reviews": 3,
     "city": "רעננה",
     "phone": "+972 50-451-1000",
     "website": "https://perfect-rami.co.il/",
     "placeId": "ChIJB9--QI85HRURwAosElYM1BI",
     "lat": 32.1899,
     "lng": 34.8745,
     "category": "ספק סוככים"
    },
    {
     "name": "דורון איש החלונות | תיקון תריסים חשמליים | שירות אדיב ומקצועי 24/7 | שירות בבית הלקוח בלבד.",
     "score": 5,
     "reviews": 37,
     "city": "רעננה",
     "phone": "+972 52-374-3737",
     "website": "http://www.windowsman.org/",
     "placeId": "ChIJ0__fi1Q5HRUR1lxSEiynT6A",
     "lat": 32.1824,
     "lng": 34.8776,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "אלומיניום השלום",
     "score": 5,
     "reviews": 14,
     "city": "הרצליה",
     "phone": "+972 50-759-5694",
     "website": "",
     "placeId": "ChIJYehEoZRHHRURrgPIZ7ng2X4",
     "lat": 32.1758,
     "lng": 34.856,
     "category": "ספק אלומיניום"
    },
    {
     "name": "פרגולות אלומיניום",
     "score": 5,
     "reviews": 38,
     "city": "כפר סבא",
     "phone": "+972 79-580-5543",
     "website": "",
     "placeId": "ChIJw76dM1M4HRURM3QSXlHqr3s",
     "lat": 32.1826,
     "lng": 34.9047,
     "category": "ספק אלומיניום"
    },
    {
     "name": "א.מ.ש אלומיניום - עבודות אלומיניום במחיר משתלם!",
     "score": 3.7,
     "reviews": 3,
     "city": "הרצליה",
     "phone": "+972 72-390-2110",
     "website": "https://aloni-alum.co.il/",
     "placeId": "ChIJwe-Jl-5HHRURerlXyd9_c1Q",
     "lat": 32.1737,
     "lng": 34.8502,
     "category": "ספק אלומיניום"
    },
    {
     "name": "תריסי בני",
     "score": 4.6,
     "reviews": 36,
     "city": "הרצליה",
     "phone": "+972 52-256-2031",
     "website": "http://www.trisi-beni.com/",
     "placeId": "ChIJORWtnvtHHRURxtMB72sLIng",
     "lat": 32.1738,
     "lng": 34.8545,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "אבקל תיקון תריסים ואלומינים",
     "score": 3.7,
     "reviews": 15,
     "city": "כפר סבא",
     "phone": "+972 54-800-8098",
     "website": "",
     "placeId": "ChIJBcxCVgo5HRURvmaGQeZVSLM",
     "lat": 32.179,
     "lng": 34.9054,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "חלונות אלומיניום בכפר סבא חלונות ותריסים",
     "score": 2.3,
     "reviews": 3,
     "city": "כפר סבא",
     "phone": "+972 50-808-7001",
     "website": "",
     "placeId": "ChIJV0pMm7Q5HRURwChceffxdQs",
     "lat": 32.1753,
     "lng": 34.9087,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אלום שי לי",
     "score": 5,
     "reviews": 2,
     "city": "כפר סבא",
     "phone": "+972 54-564-4899",
     "website": "https://www.facebook.com/alum.shaily",
     "placeId": "ChIJryq-az05HRURAj5WBbpdIaA",
     "lat": 32.1727,
     "lng": 34.9095,
     "category": "חלון אלומיניום"
    }
   ]
  },
  {
   "id": "rishon",
   "name": "אולם ראשון לציון",
   "lat": 31.973,
   "lng": 34.792,
   "places": [
    {
     "name": "אלום לירן עבודות אלומיניום",
     "score": 5,
     "reviews": 43,
     "city": "בת ים",
     "phone": "+972 53-928-8188",
     "website": "https://www.alumliran.co.il/",
     "placeId": "ChIJCbZK7l6zAhURBGqEbAhqalw",
     "lat": 32.0096,
     "lng": 34.7497,
     "category": "ספק חלונות"
    },
    {
     "name": "ג'קי משה עבודות אלומיניום וזכוכית",
     "score": 4.8,
     "reviews": 76,
     "city": "קרית אונו",
     "phone": "+972 50-910-8108",
     "website": "",
     "placeId": "ChIJ_xkf0T9LHRURdNoukRolslE",
     "lat": 32.0649,
     "lng": 34.853,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אוריאל עבודות אלומיניום",
     "score": 5,
     "reviews": 18,
     "city": "גבעתיים",
     "phone": "+972 50-884-5700",
     "website": "",
     "placeId": "ChIJJ2vjcnNLHRURPLnT00k98aA",
     "lat": 32.0861,
     "lng": 34.8174,
     "category": "חלון אלומיניום"
    },
    {
     "name": "חיים אלומיניום - תיקון תריסים, חלונות ממ\"ד והתקנות",
     "score": 4.9,
     "reviews": 26,
     "city": "פתח תקווה",
     "phone": "+972 52-775-0046",
     "website": "https://haimbiton.co.il/",
     "placeId": "ChIJM8p8r8ssyqsRAiP0XHyUzjg",
     "lat": 32.0866,
     "lng": 34.851,
     "category": "ספק חלונות"
    },
    {
     "name": "עופר אביזרים ואלומיניום",
     "score": 4.6,
     "reviews": 10,
     "city": "בני ברק",
     "phone": "+972 3-510-5107",
     "website": "http://www.ofer.biz/",
     "placeId": "ChIJQV4zuEBLHRUR8FyNAQzGzyE",
     "lat": 32.099,
     "lng": 34.832,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אור - זיו אלומניום בע\"מ יצור חלונות, תריסים, ודלתות אלומיניום",
     "score": 5,
     "reviews": 19,
     "city": "פתח תקווה",
     "phone": "+972 3-616-5855",
     "website": "",
     "placeId": "ChIJn_F1G4lJHRURLcrtXz-EKTk",
     "lat": 32.0958,
     "lng": 34.8512,
     "category": "ספק חלונות"
    },
    {
     "name": "איציק עבודות אלומיניום ומקלחונים",
     "score": 5,
     "reviews": 37,
     "city": "פתח תקווה",
     "phone": "+972 50-223-2840",
     "website": "",
     "placeId": "ChIJZ9PP69E3HRURBtsUwsqPbtY",
     "lat": 32.0933,
     "lng": 34.8857,
     "category": "חלון אלומיניום"
    },
    {
     "name": "האחים לביא חלונות אלומיניום וסורגים שקופים",
     "score": 5,
     "reviews": 10,
     "city": null,
     "phone": "+972 54-919-5935",
     "website": "https://laviwindows.wixsite.com/website-1",
     "placeId": "ChIJp3IDzw3Dr4IRbez-PNWmQ_E",
     "lat": 32.1149,
     "lng": 34.871,
     "category": "חלון אלומיניום"
    },
    {
     "name": "סוככים למרפסת - סוכך זרועות, מסך,מסילות, זיפטראק, מרקיזות ועוד | פרגולות אלומיניום - סוככי תבל",
     "score": 4.8,
     "reviews": 197,
     "city": "רמת השרון",
     "phone": "+972 3-540-8022",
     "website": "https://stb.co.il/",
     "placeId": "ChIJ17IhjUhIHRUR4CtDww18y-I",
     "lat": 32.1339,
     "lng": 34.8411,
     "category": "ספק סוככים"
    },
    {
     "name": "פרגולות אלומיניום",
     "score": 5,
     "reviews": 1,
     "city": "רמת השרון",
     "phone": "",
     "website": "",
     "placeId": "ChIJC_-QbzVIHRURxLI3SKEM2P0",
     "lat": 32.1345,
     "lng": 34.8382,
     "category": null
    },
    {
     "name": "התריס - תיקון תריסים חשמליים",
     "score": 5,
     "reviews": 1,
     "city": "הרצליה",
     "phone": "+972 1-800-200-207",
     "website": "",
     "placeId": "ChIJIcWhEPJIHRURfcCQlv3Z_Tc",
     "lat": 32.158,
     "lng": 34.8082,
     "category": "ספק אלומיניום"
    },
    {
     "name": "מר אלומיניום",
     "score": 5,
     "reviews": 8,
     "city": "הרצליה",
     "phone": "+972 52-467-7707",
     "website": "https://www.mr-aluminium.co.il/",
     "placeId": "ChIJj5K_kFBJHRURx-VL3QPImtw",
     "lat": 32.1619,
     "lng": 34.8259,
     "category": "ספק אלומיניום"
    },
    {
     "name": "ווינקס אלומיניום בע\"מ",
     "score": 1,
     "reviews": 2,
     "city": "הרצליה",
     "phone": "+972 9-954-6220",
     "website": "",
     "placeId": "ChIJif1v-oxIHRURh0ikX9TUox4",
     "lat": 32.1639,
     "lng": 34.8104,
     "category": "ספק אלומיניום"
    },
    {
     "name": "ברק סוככים ופרגולות",
     "score": 2.8,
     "reviews": 28,
     "city": "הרצליה",
     "phone": "+972 9-957-0505",
     "website": "http://www.barak-group.co.il/",
     "placeId": "ChIJvYaH-YxIHRUR6wHDOoSaAIg",
     "lat": 32.1639,
     "lng": 34.8104,
     "category": "שירות הצללת חלונות"
    },
    {
     "name": "כוכב אלומיניום",
     "score": 4.3,
     "reviews": 14,
     "city": "הרצליה",
     "phone": "",
     "website": "https://cochav.co.il/",
     "placeId": "ChIJfWum-363AhUR7uxoqj-Cr5I",
     "lat": 32.1643,
     "lng": 34.8125,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "ווינדו פיקס",
     "score": 4,
     "reviews": 4,
     "city": "הרצליה",
     "phone": "+972 53-573-2115",
     "website": "",
     "placeId": "ChIJC5cMCEpJHRUR0OK9c_G0NSU",
     "lat": 32.1655,
     "lng": 34.8118,
     "category": "חלון אלומיניום"
    },
    {
     "name": "אומנות האלומיניום",
     "score": 4.2,
     "reviews": 17,
     "city": "הרצליה",
     "phone": "+972 50-538-1828",
     "website": "https://www.shaul-aluminium.co.il/",
     "placeId": "ChIJzX81dW5IHRURZX2pBbI26Pc",
     "lat": 32.1628,
     "lng": 34.8347,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "אלומיניום בקליק פרגולות אלומיניום חלונות שערים גדרות",
     "score": 5,
     "reviews": 2,
     "city": "הוד השרון",
     "phone": "+972 55-930-2133",
     "website": "",
     "placeId": "ChIJa4aEmo83HRURDZstuFwLEJc",
     "lat": 32.1471,
     "lng": 34.8947,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אלומין",
     "score": 5,
     "reviews": 6,
     "city": "הרצליה",
     "phone": "+972 9-956-2174",
     "website": "",
     "placeId": "ChIJgTgbHfNHHRUR9XjRsr0nA08",
     "lat": 32.1622,
     "lng": 34.8529,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "תריסי שירי",
     "score": 4.3,
     "reviews": 12,
     "city": "הוד השרון",
     "phone": "+972 50-552-8620",
     "website": "https://www.facebook.com/trisi-shiri",
     "placeId": "ChIJB1ghDSY4HRURk7m6D6lKOlM",
     "lat": 32.1598,
     "lng": 34.8943,
     "category": "חלון אלומיניום"
    },
    {
     "name": "א.מ.ש אלומיניום - עבודות אלומיניום במחיר משתלם!",
     "score": 3.7,
     "reviews": 3,
     "city": "הרצליה",
     "phone": "+972 72-390-2110",
     "website": "https://aloni-alum.co.il/",
     "placeId": "ChIJwe-Jl-5HHRURerlXyd9_c1Q",
     "lat": 32.1737,
     "lng": 34.8502,
     "category": "ספק אלומיניום"
    },
    {
     "name": "אבי אלומיניום - מגשימים חלונות",
     "score": 5,
     "reviews": 65,
     "city": null,
     "phone": "+972 55-995-5888",
     "website": "",
     "placeId": "ChIJXaXPmneF1qERWGRxJ4hhldo",
     "lat": 32.1653,
     "lng": 34.882,
     "category": "חלון אלומיניום"
    },
    {
     "name": "תריסי בני",
     "score": 4.6,
     "reviews": 36,
     "city": "הרצליה",
     "phone": "+972 52-256-2031",
     "website": "http://www.trisi-beni.com/",
     "placeId": "ChIJORWtnvtHHRURxtMB72sLIng",
     "lat": 32.1738,
     "lng": 34.8545,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "אלומיניום השלום",
     "score": 5,
     "reviews": 14,
     "city": "הרצליה",
     "phone": "+972 50-759-5694",
     "website": "",
     "placeId": "ChIJYehEoZRHHRURrgPIZ7ng2X4",
     "lat": 32.1758,
     "lng": 34.856,
     "category": "ספק אלומיניום"
    },
    {
     "name": "דורון איש החלונות | תיקון תריסים חשמליים | שירות אדיב ומקצועי 24/7 | שירות בבית הלקוח בלבד.",
     "score": 5,
     "reviews": 37,
     "city": "רעננה",
     "phone": "+972 52-374-3737",
     "website": "http://www.windowsman.org/",
     "placeId": "ChIJ0__fi1Q5HRUR1lxSEiynT6A",
     "lat": 32.1824,
     "lng": 34.8776,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "אלום שי לי",
     "score": 5,
     "reviews": 2,
     "city": "כפר סבא",
     "phone": "+972 54-564-4899",
     "website": "https://www.facebook.com/alum.shaily",
     "placeId": "ChIJryq-az05HRURAj5WBbpdIaA",
     "lat": 32.1727,
     "lng": 34.9095,
     "category": "חלון אלומיניום"
    },
    {
     "name": "רויאל אלומיניום",
     "score": 5,
     "reviews": 20,
     "city": "שדי חמד",
     "phone": "+972 52-470-5558",
     "website": "",
     "placeId": "ChIJgWgTi7cxHRUR5u9PVo9eRFM",
     "lat": 32.1588,
     "lng": 34.9395,
     "category": "שירות התקנת חלונות"
    },
    {
     "name": "חלונות אלומיניום בכפר סבא חלונות ותריסים",
     "score": 2.3,
     "reviews": 3,
     "city": "כפר סבא",
     "phone": "+972 50-808-7001",
     "website": "",
     "placeId": "ChIJV0pMm7Q5HRURwChceffxdQs",
     "lat": 32.1753,
     "lng": 34.9087,
     "category": "חלון אלומיניום"
    },
    {
     "name": "רמי פרגולות אלומיניום",
     "score": 3,
     "reviews": 3,
     "city": "רעננה",
     "phone": "+972 50-451-1000",
     "website": "https://perfect-rami.co.il/",
     "placeId": "ChIJB9--QI85HRURwAosElYM1BI",
     "lat": 32.1899,
     "lng": 34.8745,
     "category": "ספק סוככים"
    },
    {
     "name": "אבקל תיקון תריסים ואלומינים",
     "score": 3.7,
     "reviews": 15,
     "city": "כפר סבא",
     "phone": "+972 54-800-8098",
     "website": "",
     "placeId": "ChIJBcxCVgo5HRURvmaGQeZVSLM",
     "lat": 32.179,
     "lng": 34.9054,
     "category": "שירות התקנת חלונות"
    }
   ]
  }
 ]
};
